package cn.ningxy.rqui.sys.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Collection;

/**
 * @TableName user
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails, Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * 用户ID
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Integer id;
    /**
     * 角色ID
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Integer roleId;
    /**
     * 手机号
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String phone;
    /**
     * 用户名
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String userName;
    /**
     * 密码
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String pwd;
    /**
     * 真名
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String realName;
    /**
     * 性别
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Byte gender;
    /**
     * 身份证号
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String identityNumber;
    /**
     * 学生类别(本科生/研究生)
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Byte type;
    /**
     * 地址
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String address;
    /**
     * 学校/单位
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String university;
    /**
     * 邮箱
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String email;
    /**
     * 头像/照片路径
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private String avatarSrc;
    /**
     * 生日
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private LocalDate birthday;
    /**
     * 是否启用
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Boolean isEnabled;
    /**
     * 是否锁定
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private Boolean isLocked;
    /**
     * GMT
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private LocalDate createTime;
    /**
     * GMT
     *
     * @mbg.generated Tue Jan 26 14:50:11 CST 2021
     */
    private LocalDate updateTime;

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }

    @Override
    public String getPassword() {
        return pwd;
    }

    @Override
    public String getUsername() {
        return userName;
    }

    public String getUserName() {
        return userName;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return !isLocked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return isEnabled;
    }
}